//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//
//     Zmiany w tym pliku mogą powodować niepoprawne działanie i zostaną utracone w przypadku
//     wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Account
{


    public partial class Lockout
    {
    }
}
