//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//
//     Zmiany w tym pliku mogą być przyczyną niepoprawnego zachowania i zostaną utracone w przypadku
//     ponownego wygenerowania kodu. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Account {
    
    
    public partial class Manage {
        
        /// <summary>
        /// Kontrolka successMessage.
        /// </summary>
        /// <remarks>
        /// Pole generowane automatycznie.
        /// Aby zmodyfikować, przenieś deklarację pola z pliku projektanta do pliku związanego z kodem.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder successMessage;
        
        /// <summary>
        /// Kontrolka ChangePassword.
        /// </summary>
        /// <remarks>
        /// Pole generowane automatycznie.
        /// Aby zmodyfikować, przenieś deklarację pola z pliku projektanta do pliku związanego z kodem.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink ChangePassword;
        
        /// <summary>
        /// Kontrolka CreatePassword.
        /// </summary>
        /// <remarks>
        /// Pole generowane automatycznie.
        /// Aby zmodyfikować, przenieś deklarację pola z pliku projektanta do pliku związanego z kodem.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink CreatePassword;
        
        /// <summary>
        /// Kontrolka PhoneNumber.
        /// </summary>
        /// <remarks>
        /// Pole generowane automatycznie.
        /// Aby zmodyfikować, przenieś deklarację pola z pliku projektanta do pliku związanego z kodem.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label PhoneNumber;
    }
}
