//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//
//     Zmiany w tym pliku mogą być przyczyną niepoprawnego zachowania i zostaną utracone w przypadku
//     ponownego wygenerowania kodu. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Account {
    
    
    public partial class Register {
        
        /// <summary>
        /// Kontrolka ErrorMessage.
        /// </summary>
        /// <remarks>
        /// Pole generowane automatycznie.
        /// Aby zmodyfikować, przenieś deklarację pola z pliku projektanta do pliku związanego z kodem.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ErrorMessage;
        
        /// <summary>
        /// Kontrolka Email.
        /// </summary>
        /// <remarks>
        /// Pole generowane automatycznie.
        /// Aby zmodyfikować, przenieś deklarację pola z pliku projektanta do pliku związanego z kodem.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Email;
        
        /// <summary>
        /// Kontrolka Password.
        /// </summary>
        /// <remarks>
        /// Pole generowane automatycznie.
        /// Aby zmodyfikować, przenieś deklarację pola z pliku projektanta do pliku związanego z kodem.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Password;
        
        /// <summary>
        /// Kontrolka ConfirmPassword.
        /// </summary>
        /// <remarks>
        /// Pole generowane automatycznie.
        /// Aby zmodyfikować, przenieś deklarację pola z pliku projektanta do pliku związanego z kodem.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ConfirmPassword;
    }
}
